### ISSUE TITLE
4-esert

### ISSUE THREAD

**Issue by hegyhati** [Teaching-projects/SZE-Dontes-2017-Vizsgaidoszak#1]
- modellbol a 2..49-ek kiirtasa
 - redundans valtozok (`nemTanul`, `nemTanulLevizsgazott`) kigyomlalasa

**Comment by unyadavid** [comment]
Megcsináltam ezeket, viszont lehet valami hiányzik még, mert nagyon lassan fut.

**Comment by hegyhati** [comment]
@unyadavid 
 - A 49-et is szedd majd ki modell fajlba. 
 - Ekezetes betuket irtsd ki a kommentekbol, vagy legyen UTF8.
 - `EgyNapEgyTargybolTanulasVagyVizsga` Ezt amugy egybevonhatod az ezt megelozovel, ha ott `n1>=n`-t irsz szima nagyobb helyett.
 - Ugyanez a korlatozas igazabol benne  van az eztk ovetkezoben is, szoval felesleges :-)
 - `HaVizsgazomNemTanulok`, ez a korlatozas is ugyanaz, mehet a kukaba
 
Ettol fuggetlenul rendben vannak, amiket kertem, beirom a 4-est, de ezeket majd meg pushold fel mindenkepp.
